version: 2

sources:
  - name: raw
    schema: gz_raw_data # Ensure this matches the dataset where your raw_gz_ tables reside
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
            tests:
              - not_null
          - name: pdt_id # Assuming this is the correct column name in raw_gz_sales for product ID
            description: foreign key to product
            tests:
              - not_null
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for a given order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id # Ensure this matches your actual column name in raw_gz_product
            description: Primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product

      - name: ship
        identifier: raw_gz_ship
        description: shipping data for Greenweez orders
        columns:
          - name: orders_id # Ensure this matches your actual column name in raw_gz_ship
            description: Primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the distribution centre/warehouse
          - name: ship_cost
            description: shipping cost paid by Greenweez to the carrier/logistics provider

      - name: adwords # This is the dbt source name
        identifier: raw_gz_adwords # This is the actual table name in BigQuery
        description: Raw data from Google Adwords campaigns
        columns:
          - name: date_date
            description: Date of the ad campaign data
          - name: paid_source
            description: The platform where the ad was run (e.g., 'adwords')
          - name: campaign_key
            description: Unique identifier for the campaign
          - name: camPGN_name
            description: Original name of the ad campaign (will be renamed in staging)
          - name: ads_cost
            description: Cost of the ad campaign
          - name: impression
            description: Number of impressions the ad received
          - name: click
            description: Number of clicks the ad received

      - name: bing
        identifier: raw_gz_bing
        description: Raw data from Bing Ads campaigns
        columns:
          - name: date_date
            description: Date of the ad campaign data
          - name: paid_source
            description: The platform where the ad was run (e.g., 'bing')
          - name: campaign_key
            description: Unique identifier for the campaign
          - name: camPGN_name
            description: Original name of the ad campaign (will be renamed in staging)
          - name: ads_cost
            description: Cost of the ad campaign
          - name: impression
            description: Number of impressions the ad received
          - name: click
            description: Number of clicks the ad received

      - name: criteo
        identifier: raw_gz_criteo
        description: Raw data from Criteo campaigns
        columns:
          - name: date_date
            description: Date of the ad campaign data
          - name: paid_source
            description: The platform where the ad was run (e.g., 'criteo')
          - name: campaign_key
            description: Unique identifier for the campaign
          - name: camPGN_name
            description: Original name of the ad campaign (will be renamed in staging)
          - name: ads_cost
            description: Cost of the ad campaign
          - name: impression
            description: Number of impressions the ad received
          - name: click
            description: Number of clicks the ad received

      - name: facebook
        identifier: raw_gz_facebook
        description: Raw data from Facebook Ads campaigns
        columns:
          - name: date_date
            description: Date of the ad campaign data
          - name: paid_source
            description: The platform where the ad was run (e.g., 'facebook')
          - name: campaign_key
            description: Unique identifier for the campaign
          - name: camPGN_name
            description: Original name of the ad campaign (will be renamed in staging)
          - name: ads_cost
            description: Cost of the ad campaign
          - name: impression
            description: Number of impressions the ad received
          - name: click
            description: Number of clicks the ad received

models:
  
    - name: int_campaigns # Now a list item under my_new_project
      description: Combined and cleaned ad campaign data from all sources.
      columns:
        - name: date_date
          description: Date of the ad campaign data.
          tests:
            - not_null
        - name: paid_source
          description: The platform where the ad was run (e.g., 'adwords', 'bing', 'criteo', 'facebook').
          tests:
            - not_null
        - name: campaign_key
          description: Unique identifier for the campaign.
          tests:
            - not_null
        - name: campaign_name
          description: Name of the ad campaign.
        - name: ads_cost
          description: Cost of the ad campaign.
          tests:
            - not_null
           
        - name: impression
          description: Number of impressions the ad received.
          tests:
            - not_null
            
        - name: click
          description: Number of clicks the ad received.
          tests:
            - not_null
           
      
    - name: int_campaigns_day # Now a list item under my_new_project
      description: Daily aggregated ad campaign data.
      columns:
        - name: date_date
          description: The date of the aggregated campaign data.
          tests:
            - not_null
            - unique # date_date should be unique in this daily aggregation
        - name: daily_ads_cost
          description: Total ad cost for the day.
          tests:
            - not_null
           
        - name: daily_impressions
          description: Total impressions for the day.
          tests:
            - not_null
           
        - name: daily_clicks
          description: Total clicks for the day.
          tests:
            - not_null
         
    - name: finance_days # Assuming this model is also defined this way
      description: Daily financial aggregated data for the finance team.
      columns:
        - name: date_date
          description: The date of the aggregated data.
          tests:
            - not_null
            - unique
        - name: nb_transactions
          description: Number of unique transactions per day.
          tests:
            - not_null
           
        - name: revenue
          description: Total revenue for the day.
          tests:
            - not_null
            
        - name: margin
          description: Total margin for the day (revenue - purchase_cost).
          tests:
            - not_null
        - name: operational_margin
          description: Total operational margin for the day (margin + shipping_fee - log_cost - ship_cost).
          tests:
            - not_null
        - name: purchase_cost
          description: Total purchase cost for the day.
          tests:
            - not_null
           
        - name: shipping_fee
          description: Total shipping fee for the day.
          tests:
            - not_null
            
        - name: log_cost
          description: Total logistics cost for the day.
          tests:
            - not_null
            
        - name: ship_cost
          description: Total shipping cost for the day.
          tests:
            - not_null
           
        - name: quantity
          description: Total quantity of products sold for the day.
          tests:
            - not_null
            
        - name: average_basket
          description: Average basket value for the day (revenue / number of transactions).
          tests:
            - not_null
            